### ISSUE TITLE
Jason lessons learned on salt

### ISSUE THREAD

**Issue by alan-cugler** [terminal-labs/tl_web#132]

**Comment by jtraub91** [comment]
hey I said that once

**Comment by jtraub91** [comment]
For context, the over-arching issue is that we were seeing high amounts of minion failures for running the configurable test state against large groups of minions. The failure mode was that minions would _return_ with a traceback indicating something like "message timed out" or "authentication timeout" or not return at all. At the same time, the issue would not occur for salt commands (i.e. `test.ping` to all minions would run with near 100% success), only states. Before disabling SSC external pillar, this would happen for targeting groups of only hundreds of minions. After disabling pillar the problem still occurs, but only when targeting thousands of minions. Keep in mind, it does not appear to be a minion side issue, since targeting these failed minions individually, the error wouldn't occur. Only when targeting many minions at once, it would fail on a random subset of them, indicating it has to do with high load on the master causing timeout errors. The master clusters had 32 cpus and 32 gb ram, and the minion counts would vary by cluster from 3000 to 7000 minions. Also of note, is that more than 50% of the minions were Windows minions.

**Comment by jtraub91** [comment]
The part where SSC external pillar is apparently causing issues (forcing us to move to local pillar) is a bug VMware is currently working on

**Comment by jtraub91** [comment]
test comment
